import { BLOG_PATH } from "@/content.config";
import { slugifyStr } from "./slugify";

/**
 * Get full path of a blog post.
 *
 * Posts are co-located in folders: `year/slug/lang.md(x)`.
 * The URL is derived from the directory structure, stripping the
 * language filename (e.g. `es.mdx`) so that
 * `src/data/blog/2022/my-post/es.mdx` → `/es/blog/2022/my-post`.
 *
 * If a custom `slug` is provided in frontmatter, it replaces only the
 * last segment (the post name), keeping the year prefix intact.
 * E.g. slug: "how-i-took-a-nodejs-process" with filePath containing
 * `2022/como-pase.../en.mdx` → `/blog/2022/how-i-took-a-nodejs-process`.
 *
 * @param id - id of the blog post (generated by Astro glob loader)
 * @param filePath - the blog post full file location
 * @param includeBase - whether to include `/blog` prefix in return value
 * @param lang - language of the post (en or es)
 * @param slug - optional custom slug that overrides the folder-derived post name
 * @returns blog post path
 */
export function getPath(
  id: string,
  filePath: string | undefined,
  includeBase = true,
  lang: "en" | "es" = "en",
  slug?: string
) {
  const pathSegments = filePath
    ?.replace(BLOG_PATH, "")
    .split("/")
    .filter(path => path !== "")
    .filter(path => !path.startsWith("_"))
    .slice(0, -1) // remove the filename (es.md, en.mdx, etc.)
    .map(segment => slugifyStr(segment));

  const langPrefix = lang === "es" ? "/es" : "";
  const basePath = includeBase ? `${langPrefix}/blog` : "";

  if (!pathSegments || pathSegments.length < 1) {
    // Fallback: derive slug from id, stripping lang suffix (e.g. "my-post/en" → "my-post")
    const idSegments = id.split("/").filter(s => !["en", "es"].includes(s));
    if (slug) {
      idSegments[idSegments.length - 1] = slugifyStr(slug);
    }
    return [basePath, ...idSegments].join("/");
  }

  if (slug) {
    pathSegments[pathSegments.length - 1] = slugifyStr(slug);
  }

  return [basePath, ...pathSegments].join("/");
}
