name: Deploy website

on:
  push:
    branches:
      - main

env:
  PLUGIN_NAME: obsidian-pending-notes # Change this to match the id of your plugin.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build:ci
