name: Deploy website

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build:ci

      - name: Deploy on branch
          run: git config user.name "Ulises Santana" && 
            git config user.email "ulisesantana@gmail.com" && 
            npm run deploy:gh-pages
